### ISSUE TITLE
Support for + as separator

### ISSUE THREAD

**Issue by emilv** [olssonm/identity-number#14]
The `+` character replaces the `-` when a person turns 100 years old: https://lagen.nu/1991:481#P18S2

**Comment by olssonm** [comment]
Wow, that's news to me – will definitely take a look at it. Thanks!

**Comment by olssonm** [comment]
A new release is now available; https://github.com/olssonm/identity-number/releases/tag/v5.1 – which allows the use of "+" as a hyphen/seperator.

Now, as the structure of this project is quite clunky at this point the validation doesn't actually check that the personnummer under validation is 100+ years – "+" is just always allowed. Will have to look into this on the next major release instead when I have the time to refactor/rewrite more of the code.

Feel free to test it out and open a new issue if you encounter any troubles.
