### ISSUE TITLE
Add support for "samordningsnummer"

### ISSUE THREAD

**Issue by trippo80** [olssonm/identity-number#7]
These are given to persons who haven't received a real ssn - to be used in contact with authorities.

In short - you add 60 to the last two digits in the birth date. If the person is born 1985-04-30, their "samordningsnummer" would start with 19850460.

You can read more about this at [https://sv.wikipedia.org/wiki/Personnummer_i_Sverige#Andra_nummer](https://sv.wikipedia.org/wiki/Personnummer_i_Sverige#Andra_nummer)
or
[https://sv.wikipedia.org/wiki/Samordningsnummer](https://sv.wikipedia.org/wiki/Samordningsnummer)

Thanks!

**Comment by olssonm** [comment]
Hey, great idea! Will read up on and look into it. Thanks!

**Comment by olssonm** [comment]
A beta-release is now available at https://github.com/olssonm/identity-number/releases/tag/v4.0-beta.

The update should enable the validation of "samordningsnummer". You wouldn't happen to have the ability to test them out with "real" numbers?

A proper release will be available soon.

Anyhow, the download is available via `composer require olssonm/identity-number "~4.0"`. Make sure `"minimum-stability"` is set to `"beta"` or similar in the composer.json.

Complete documentation for the new version is available at https://github.com/olssonm/identity-number/blob/master/README.md.

**Comment by olssonm** [comment]
Ping @trippo80 on the previous post... =)

**Comment by trippo80** [comment]
Hi @olssonm !

Thanks for the update. Unfortunately I don't have any real data to test with. I'm currently building a new application which has this requirement. But I guess it would work by using any real ssn and just add 60 to the days value.

I don't have time to test this at the moment - but I'll make sure to do that once I get a bit further into the project (basically - when I build the view where this would be used).

Thanks again!

**Comment by olssonm** [comment]
Thanks for the response @trippo80.

Yeah, just adding 60 to the birthday doesn't work I think; the four last digits are control digits and those would fail if you just did that. So the current validator assumes that those four digits are built with birthdays between ~61-91.

But yes, let's test that in the future – I might be wrong about this =)

**Comment by trippo80** [comment]
Ah yes - of course. You're right. I forgot about the control digits :)

**Comment by olssonm** [comment]
A live 4.0-version are now up (https://github.com/olssonm/identity-number/releases/tag/v4.0), closing this issue and hopes that it works once the time comes to handle this =)

Else you are always welcome to open up a new ticket, of course.
